"""C++ language handler for AutoPerf v2.

The handler generates a self-contained harness around the user's kernel
source.  The harness supports two run modes:

    ./binary --test   Run correctness checks, exit 0 on success.
    ./binary --bench  Run a tight benchmark loop, emit JSON on stdout.

The kernel source is written to a file and ``#include``d by the harness so
that the optimiser can see the implementation.  The header (if it exists)
is also included so that the harness can call the kernel's public API.

The harness is generated by parsing the actual function signature from the
kernel source, so it works with any kernel that follows standard C/C++
function declaration conventions.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

from languages.base import LanguageHandler

# ---------------------------------------------------------------------------
# Function signature parsing
# ---------------------------------------------------------------------------

@dataclass
class FuncParam:
    """A single parsed function parameter."""
    full_type: str   # e.g. "const float*" -- the type WITHOUT the name
    name: str        # e.g. "data"
    is_pointer: bool
    is_const: bool
    base_type: str   # e.g. "float"
    is_size: bool    # True if the type is size_t / int / unsigned and name
                     # hints at a count/length/size/n


@dataclass
class FuncSig:
    """A parsed function signature."""
    return_type: str      # e.g. "float" or "void"
    name: str             # e.g. "reduce"
    params: List[FuncParam]
    returns_value: bool   # True when return_type is not void


_SIZE_NAMES = re.compile(r'^(n|N|sz|size|len|length|count|rows|cols|dim|M|K)$')
_SIZE_TYPES = {'size_t', 'int', 'unsigned', 'unsigned int', 'long', 'unsigned long'}


def _parse_param(raw: str) -> FuncParam:
    """Parse a single C/C++ parameter declaration like ``const float* data``."""
    raw = raw.strip()
    is_const = 'const' in raw
    is_pointer = '*' in raw

    # Normalise: strip const, *, &
    cleaned = raw.replace('const ', '').replace('const', '').replace('*', ' ').replace('&', ' ').strip()
    parts = cleaned.split()
    if len(parts) >= 2:
        name = parts[-1]
        base_type = ' '.join(parts[:-1])
    elif len(parts) == 1:
        # unnamed parameter -- synthesise a name
        name = '_unnamed'
        base_type = parts[0]
    else:
        name = '_unnamed'
        base_type = 'int'

    # Reconstruct the type string (without the parameter name)
    type_str = ''
    if is_const:
        type_str = 'const '
    type_str += base_type
    if is_pointer:
        type_str += '*'

    is_size = (base_type in _SIZE_TYPES) and (not is_pointer) and bool(_SIZE_NAMES.match(name))

    return FuncParam(
        full_type=type_str,
        name=name,
        is_pointer=is_pointer,
        is_const=is_const,
        base_type=base_type,
        is_size=is_size,
    )


def parse_function_signature(source: str) -> Optional[FuncSig]:
    """Find the first non-static, non-inline-helper function in *source*.

    Returns ``None`` if no suitable function is found.
    """
    # Match:  <return_type> <name>(<params>) {
    # We skip lines starting with 'static' or '#'.
    pattern = re.compile(
        r'^\s*'                          # leading whitespace
        r'(?!static\b)'                  # not static
        r'(?!#)'                         # not preprocessor
        r'([\w\s\*&:]+?)'               # return type  (group 1)
        r'\b(\w+)\s*'                    # function name (group 2)
        r'\(([^)]*)\)\s*\{',             # parameters   (group 3)
        re.MULTILINE,
    )
    for m in pattern.finditer(source):
        ret_type = m.group(1).strip()
        fname = m.group(2).strip()
        params_raw = m.group(3).strip()

        # Skip main, helpers, constructors
        if fname in ('main', 'now_ns', 'run_tests', 'run_bench'):
            continue

        params = []
        if params_raw:
            for p in params_raw.split(','):
                params.append(_parse_param(p))

        returns_value = ret_type != 'void'

        return FuncSig(
            return_type=ret_type,
            name=fname,
            params=params,
            returns_value=returns_value,
        )
    return None


# ---------------------------------------------------------------------------
# Harness code generation from parsed signature
# ---------------------------------------------------------------------------

def _generate_test_and_bench(sig: FuncSig) -> dict[str, str]:
    """Generate test_body, bench_setup, bench_call, bench_teardown for *sig*.

    This handles the four known kernel patterns:
      - reduce(const float* data, size_t n) -> float
      - dot(const float* a, const float* b, size_t n) -> float
      - axpy(float a, const float* x, float* y, size_t n) -> void
      - matmul(const float* A, const float* B, float* C, size_t N) -> void

    And falls back to a reasonable generic pattern for unknown signatures.
    """
    name = sig.name

    # Classify parameters
    scalar_params = [p for p in sig.params if not p.is_pointer and not p.is_size]
    size_params = [p for p in sig.params if p.is_size]
    const_array_params = [p for p in sig.params if p.is_pointer and p.is_const]
    mut_array_params = [p for p in sig.params if p.is_pointer and not p.is_const]

    # Determine the size variable name (use the first size param, or "N")
    size_name = size_params[0].name if size_params else 'N'

    # ----- generate test body -----
    test_lines = []
    bench_setup_lines = []
    bench_call = ''
    bench_teardown = ''

    if sig.returns_value and not mut_array_params:
        # Pattern: returns a scalar, no output arrays (reduce, dot)
        test_size = 1024

        test_lines.append('{')
        test_lines.append(f'    const size_t {size_name} = {test_size};')

        # Allocate const input arrays
        for p in const_array_params:
            test_lines.append(f'    std::vector<{p.base_type}> _vec_{p.name}({size_name});')
            test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i) _vec_{p.name}[_i] = ({p.base_type})(_i + 1);')

        # Scalar params get fixed test values
        for p in scalar_params:
            test_lines.append(f'    {p.full_type} {p.name} = ({p.base_type})2.5;')

        # Build the call expression
        call_args = []
        for p in sig.params:
            if p.is_size:
                call_args.append(size_name)
            elif p.is_pointer:
                call_args.append(f'_vec_{p.name}.data()')
            else:
                call_args.append(p.name)

        call_expr = f'{name}({", ".join(call_args)})'

        # Compute reference with a naive loop
        test_lines.append(f'    // Naive reference')
        test_lines.append(f'    {sig.return_type} expected = 0;')

        if len(const_array_params) == 1:
            # reduce-style: sum all elements
            p = const_array_params[0]
            test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i) expected += _vec_{p.name}[_i];')
        elif len(const_array_params) == 2:
            # dot-style: sum of products
            p0, p1 = const_array_params[0], const_array_params[1]
            test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i) expected += _vec_{p0.name}[_i] * _vec_{p1.name}[_i];')

        test_lines.append(f'    {sig.return_type} actual = {call_expr};')
        test_lines.append(f'    if (std::fabs((double)(expected - actual)) > 1e-1) {{')
        test_lines.append(f'        fprintf(stderr, "FAIL {name}: expected %f got %f\\n", (double)expected, (double)actual);')
        test_lines.append(f'        return 1;')
        test_lines.append(f'    }}')
        test_lines.append('}')

        # Also test with size 0
        test_lines.append('{')
        test_lines.append(f'    const size_t {size_name} = 0;')
        for p in const_array_params:
            test_lines.append(f'    std::vector<{p.base_type}> _vec_{p.name};')
        for p in scalar_params:
            test_lines.append(f'    {p.full_type} {p.name} = ({p.base_type})1.0;')
        test_lines.append(f'    {sig.return_type} actual = {call_expr};')
        test_lines.append(f'    if (std::fabs((double)actual) > 1e-6) {{')
        test_lines.append(f'        fprintf(stderr, "FAIL {name}(empty): expected 0 got %f\\n", (double)actual);')
        test_lines.append(f'        return 1;')
        test_lines.append(f'    }}')
        test_lines.append('}')

        # Bench setup
        bench_size = '1 << 20'
        bench_setup_lines.append(f'const size_t {size_name} = {bench_size};')
        for p in const_array_params:
            bench_setup_lines.append(f'std::vector<{p.base_type}> _vec_{p.name}({size_name});')
            bench_setup_lines.append(f'{{ std::mt19937 _rng(42); std::uniform_real_distribution<{p.base_type}> _d(0,1);')
            bench_setup_lines.append(f'  for (auto& _v : _vec_{p.name}) _v = _d(_rng); }}')
        for p in scalar_params:
            bench_setup_lines.append(f'{p.full_type} {p.name} = ({p.base_type})2.5;')
        bench_setup_lines.append(f'volatile {sig.return_type} _sink;')
        bench_call = f'_sink = {call_expr}'
        bench_teardown = '    (void)_sink;'

    elif not sig.returns_value and mut_array_params:
        # Pattern: void function with output array(s) (axpy, matmul)

        # Detect matmul pattern: 2 const arrays + 1 mut array + 1 size = square matmul
        is_matmul = (len(const_array_params) == 2 and len(mut_array_params) == 1
                     and len(size_params) == 1 and name in ('matmul', 'gemm', 'sgemm', 'matrix_multiply'))

        if is_matmul:
            _gen_matmul(sig, size_name, const_array_params, mut_array_params, scalar_params, test_lines, bench_setup_lines)
            call_args = []
            for p in sig.params:
                if p.is_size:
                    call_args.append(size_name)
                elif p.is_pointer:
                    call_args.append(f'_vec_{p.name}.data()')
                else:
                    call_args.append(p.name)
            call_expr = f'{name}({", ".join(call_args)})'
            bench_call = call_expr
        else:
            # Generic void-with-output: axpy-style
            test_size = 1024

            test_lines.append('{')
            test_lines.append(f'    const size_t {size_name} = {test_size};')

            for p in const_array_params:
                test_lines.append(f'    std::vector<{p.base_type}> _vec_{p.name}({size_name});')
                test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i) _vec_{p.name}[_i] = ({p.base_type})(_i + 1);')

            for p in mut_array_params:
                test_lines.append(f'    std::vector<{p.base_type}> _vec_{p.name}({size_name});')
                test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i) _vec_{p.name}[_i] = ({p.base_type})(_i * 0.5f);')

            # Reference copy for mut arrays
            for p in mut_array_params:
                test_lines.append(f'    std::vector<{p.base_type}> _ref_{p.name}(_vec_{p.name});')

            for p in scalar_params:
                test_lines.append(f'    {p.full_type} {p.name} = ({p.base_type})2.0;')

            call_args = []
            for p in sig.params:
                if p.is_size:
                    call_args.append(size_name)
                elif p.is_pointer:
                    call_args.append(f'_vec_{p.name}.data()')
                else:
                    call_args.append(p.name)
            call_expr = f'{name}({", ".join(call_args)})'

            test_lines.append(f'    // Compute naive reference')
            # For axpy: y[i] = a*x[i] + y[i]
            if name == 'axpy' and len(scalar_params) == 1 and len(const_array_params) == 1 and len(mut_array_params) == 1:
                a_name = scalar_params[0].name
                x_name = const_array_params[0].name
                y_name = mut_array_params[0].name
                test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i)')
                test_lines.append(f'        _ref_{y_name}[_i] = {a_name} * _vec_{x_name}[_i] + _ref_{y_name}[_i];')
            else:
                # Generic: we cannot compute a reference, so just run and don't crash
                test_lines.append(f'    // (generic: no reference computation, just check it does not crash)')

            test_lines.append(f'    {call_expr};')

            # Check output vs reference (only if we computed one)
            if name == 'axpy' and len(scalar_params) == 1 and len(const_array_params) == 1 and len(mut_array_params) == 1:
                y_name = mut_array_params[0].name
                test_lines.append(f'    for (size_t _i = 0; _i < {size_name}; ++_i) {{')
                test_lines.append(f'        if (std::fabs(_vec_{y_name}[_i] - _ref_{y_name}[_i]) > 1e-2f) {{')
                test_lines.append(f'            fprintf(stderr, "FAIL {name}[%zu]: expected %f got %f\\n", _i, (double)_ref_{y_name}[_i], (double)_vec_{y_name}[_i]);')
                test_lines.append(f'            return 1;')
                test_lines.append(f'        }}')
                test_lines.append(f'    }}')

            test_lines.append('}')

            # Bench setup
            bench_size = '1 << 20'
            bench_setup_lines.append(f'const size_t {size_name} = {bench_size};')
            for p in const_array_params:
                bench_setup_lines.append(f'std::vector<{p.base_type}> _vec_{p.name}({size_name});')
                bench_setup_lines.append(f'{{ std::mt19937 _rng(42); std::uniform_real_distribution<{p.base_type}> _d(0,1);')
                bench_setup_lines.append(f'  for (auto& _v : _vec_{p.name}) _v = _d(_rng); }}')
            for p in mut_array_params:
                bench_setup_lines.append(f'std::vector<{p.base_type}> _vec_{p.name}({size_name}, 0);')
            for p in scalar_params:
                bench_setup_lines.append(f'{p.full_type} {p.name} = ({p.base_type})2.5;')
            bench_call = call_expr

    else:
        # Unknown pattern: generate a minimal harness
        test_lines.append(f'fprintf(stderr, "No auto-detected tests for {name}.\\n");')
        bench_setup_lines.append('// No auto-detected benchmark setup.')
        bench_call = '(void)0'

    return {
        'test_body': '\n'.join(test_lines),
        'bench_setup': '\n'.join(bench_setup_lines),
        'bench_call': bench_call,
        'bench_teardown': bench_teardown,
    }


def _gen_matmul(sig, size_name, const_array_params, mut_array_params, scalar_params,
                test_lines, bench_setup_lines):
    """Generate test + bench setup specifically for square matmul."""
    name = sig.name
    A_name = const_array_params[0].name
    B_name = const_array_params[1].name
    C_name = mut_array_params[0].name
    base = const_array_params[0].base_type

    # --- Test: 2x2 identity * matrix ---
    test_lines.append('{')
    test_lines.append(f'    const size_t {size_name} = 2;')
    test_lines.append(f'    std::vector<{base}> _vec_{A_name} = {{1,0, 0,1}};')
    test_lines.append(f'    std::vector<{base}> _vec_{B_name} = {{5,6, 7,8}};')
    test_lines.append(f'    std::vector<{base}> _vec_{C_name}(4, 0.0f);')
    for p in scalar_params:
        test_lines.append(f'    {p.full_type} {p.name} = ({p.base_type})1.0;')

    call_args = []
    for p in sig.params:
        if p.is_size:
            call_args.append(size_name)
        elif p.is_pointer:
            call_args.append(f'_vec_{p.name}.data()')
        else:
            call_args.append(p.name)
    call_expr = f'{name}({", ".join(call_args)})'

    test_lines.append(f'    {call_expr};')
    test_lines.append(f'    {base} expected[] = {{5,6, 7,8}};')
    test_lines.append(f'    for (size_t _i = 0; _i < 4; ++_i) {{')
    test_lines.append(f'        if (std::fabs(_vec_{C_name}[_i] - expected[_i]) > 1e-4f) {{')
    test_lines.append(f'            fprintf(stderr, "FAIL {name}[%zu]: expected %f got %f\\n", _i, (double)expected[_i], (double)_vec_{C_name}[_i]);')
    test_lines.append(f'            return 1;')
    test_lines.append(f'        }}')
    test_lines.append(f'    }}')
    test_lines.append('}')

    # --- Test: 3x3 known multiplication ---
    test_lines.append('{')
    test_lines.append(f'    const size_t {size_name} = 3;')
    test_lines.append(f'    std::vector<{base}> _vec_{A_name} = {{1,2,3, 4,5,6, 7,8,9}};')
    test_lines.append(f'    std::vector<{base}> _vec_{B_name} = {{9,8,7, 6,5,4, 3,2,1}};')
    test_lines.append(f'    std::vector<{base}> _vec_{C_name}(9, 0.0f);')
    for p in scalar_params:
        test_lines.append(f'    {p.full_type} {p.name} = ({p.base_type})1.0;')
    test_lines.append(f'    {call_expr};')
    test_lines.append(f'    // Reference: naive matmul')
    test_lines.append(f'    {base} ref[9] = {{0}};')
    test_lines.append(f'    for (size_t i = 0; i < {size_name}; ++i)')
    test_lines.append(f'        for (size_t j = 0; j < {size_name}; ++j)')
    test_lines.append(f'            for (size_t k = 0; k < {size_name}; ++k)')
    test_lines.append(f'                ref[i*{size_name}+j] += _vec_{A_name}[i*{size_name}+k] * _vec_{B_name}[k*{size_name}+j];')

    # Wait -- we already mutated _vec_A and _vec_B data? No, those are const.
    # But _vec_C was written. And we used the vectors for reference computation.
    # Actually reference needs original A and B which are const_array, so the
    # vector data is unchanged. But we need to re-read _vec_A, _vec_B.
    # Actually the call modifies C only. A and B are const. So ref computation
    # using _vec_A and _vec_B after the call is fine.
    # BUT we did the call first, and THEN compute ref -- that means _vec_A, _vec_B
    # are still fine (const). But _vec_C is the output. ref uses A,B source data.
    # Wait, the ref computation reads _vec_A and _vec_B -- but those are the SAME
    # vectors we passed to the function. Since they're const in the function, the
    # data should be unchanged. So this is correct.
    # Actually, let me reorder: compute ref BEFORE the call for safety.
    # Let me just put ref first and use A_init/B_init copies.
    # Actually, simplify: compute ref from the initializer values directly.

    # The approach above has a subtle issue: we compute ref AFTER the call using
    # _vec_A and _vec_B which are the same vectors. Since A and B are const in
    # the kernel, this should be fine. Let me keep it simple.

    test_lines.append(f'    for (size_t _i = 0; _i < 9; ++_i) {{')
    test_lines.append(f'        if (std::fabs(_vec_{C_name}[_i] - ref[_i]) > 1e-2f) {{')
    test_lines.append(f'            fprintf(stderr, "FAIL {name}(3x3)[%zu]: expected %f got %f\\n", _i, (double)ref[_i], (double)_vec_{C_name}[_i]);')
    test_lines.append(f'            return 1;')
    test_lines.append(f'        }}')
    test_lines.append(f'    }}')
    test_lines.append('}')

    # Bench setup
    bench_setup_lines.append(f'const size_t {size_name} = 128;')
    bench_setup_lines.append(f'std::vector<{base}> _vec_{A_name}({size_name}*{size_name});')
    bench_setup_lines.append(f'std::vector<{base}> _vec_{B_name}({size_name}*{size_name});')
    bench_setup_lines.append(f'std::vector<{base}> _vec_{C_name}({size_name}*{size_name}, 0.0f);')
    bench_setup_lines.append(f'{{ std::mt19937 _rng(42); std::uniform_real_distribution<{base}> _d(-1,1);')
    bench_setup_lines.append(f'  for (auto& _v : _vec_{A_name}) _v = _d(_rng);')
    bench_setup_lines.append(f'  for (auto& _v : _vec_{B_name}) _v = _d(_rng); }}')


# ---------------------------------------------------------------------------
# Harness template
# ---------------------------------------------------------------------------

HARNESS_TEMPLATE = r"""
// Auto-generated by AutoPerf v2 -- do not edit.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cstddef>
#include <vector>
#include <numeric>
#include <random>
#include <string>
#include <stdexcept>
#include <time.h>

{header_include}

// Include the kernel implementation directly so the compiler can inline.
{kernel_include}

// ---- helpers ---------------------------------------------------------------

static inline double now_ns() {{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec * 1e9 + (double)ts.tv_nsec;
}}

// ---- test mode -------------------------------------------------------------

static int run_tests() {{
{test_body}
    return 0;  // all passed
}}

// ---- bench mode ------------------------------------------------------------

static void run_bench() {{
{bench_setup}

    // Auto-calibrate: find iteration count that takes >= 0.5s,
    // capped at {max_bench_iters} iters.
    int _autoperf_N = 1;
    for (;;) {{
        double _cal_start = now_ns();
        for (int _i = 0; _i < _autoperf_N; ++_i) {{
            {bench_call};
            asm volatile("" ::: "memory");
        }}
        double _cal_elapsed = now_ns() - _cal_start;
        if (_cal_elapsed >= 5e8 || _autoperf_N >= {max_bench_iters}) break;
        // Scale up: target 1s total
        int _next = (int)((1e9 / _cal_elapsed) * _autoperf_N);
        if (_next <= _autoperf_N) _next = _autoperf_N * 2;
        if (_next > {max_bench_iters}) _next = {max_bench_iters};
        _autoperf_N = _next;
    }}

    // Warm-up with the calibrated count (small fraction)
    int _warmup = _autoperf_N < 100 ? _autoperf_N : 100;
    for (int _w = 0; _w < _warmup; ++_w) {{
        {bench_call};
        asm volatile("" ::: "memory");
    }}

    // Timed loop
    double start = now_ns();
    for (int _i = 0; _i < _autoperf_N; ++_i) {{
        {bench_call};
        asm volatile("" ::: "memory");
    }}
    double end = now_ns();

    double ns_per_op = (end - start) / (double)_autoperf_N;
    printf("{{\"ns_per_op\": %.2f, \"iterations\": %d}}\n", ns_per_op, _autoperf_N);

{bench_teardown}
}}

// ---- main ------------------------------------------------------------------

int main(int argc, char** argv) {{
    if (argc < 2) {{
        fprintf(stderr, "Usage: %s --test | --bench\\n", argv[0]);
        return 2;
    }}
    if (std::string(argv[1]) == "--test")  return run_tests();
    if (std::string(argv[1]) == "--bench") {{ run_bench(); return 0; }}
    fprintf(stderr, "Unknown flag: %s\\n", argv[1]);
    return 2;
}}
"""


class CppHandler(LanguageHandler):
    """Compile and benchmark C++ kernels with raw g++."""

    COMPILER = "g++"
    STD_FLAG = "-std=c++17"
    LANGUAGE_NAME = "C++"

    def __init__(self, config):
        super().__init__(config)
        self._binary_path = os.path.join(self._workdir, "autoperf_harness")
        self._harness_path = os.path.join(self._workdir, "harness.cpp")
        self._kernel_path = os.path.join(self._workdir, "kernel.cpp")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _find_header(self) -> str | None:
        """Try to locate the matching header for the configured kernel_path."""
        kp = Path(self.config.kernel_path)
        candidates = [
            kp.parent.parent / "include" / kp.with_suffix(".hpp").name,
            kp.parent / kp.with_suffix(".hpp").name,
            kp.parent / kp.with_suffix(".h").name,
            kp.parent.parent / "include" / kp.with_suffix(".h").name,
        ]
        for c in candidates:
            if c.is_file():
                return str(c)
        return None

    def _generate_harness(
        self,
        kernel_code: str,
        header_path: str | None = None,
    ) -> str:
        """Build the harness C++ source by parsing the kernel's function signature."""

        # Parse the kernel's actual function signature
        sig = parse_function_signature(kernel_code)

        if sig is None:
            spec = {
                'test_body': '    fprintf(stderr, "No function found in kernel source.\\n");\n',
                'bench_setup': '    // No auto-detected benchmark setup.',
                'bench_call': '(void)0',
                'bench_teardown': '',
            }
        else:
            spec = _generate_test_and_bench(sig)

        # Build include directives
        header_include = ""
        if header_path:
            hdr_dest = os.path.join(self._workdir, os.path.basename(header_path))
            with open(header_path) as f:
                hdr_contents = f.read()
            with open(hdr_dest, "w") as f:
                f.write(hdr_contents)
            header_include = f'#include "{os.path.basename(header_path)}"'

        kernel_include = f'#include "{os.path.basename(self._kernel_path)}"'

        harness = HARNESS_TEMPLATE.format(
            header_include=header_include,
            kernel_include=kernel_include,
            test_body=textwrap.indent(spec["test_body"], "    "),
            bench_setup=textwrap.indent(spec["bench_setup"], "    "),
            bench_call=spec["bench_call"],
            bench_teardown=spec.get("bench_teardown", ""),
            max_bench_iters=10000000,
        )
        return harness

    def _run_sandboxed(self, args: list[str], **kwargs) -> subprocess.CompletedProcess:
        """Run a command under sandbox constraints."""
        cmd = self._sandbox_prefix() + args
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            preexec_fn=self._ulimit_preexec(),
            **kwargs,
        )

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def get_assembly(self, code: str) -> str | None:
        """Generate assembly for the kernel and return the hot function's asm.

        Returns the first ~50 lines of the function's assembly in Intel syntax,
        or None if generation fails.
        """
        try:
            asm_src = os.path.join(self._workdir, "kernel_asm.cpp")
            asm_out = os.path.join(self._workdir, "kernel.s")

            with open(asm_src, "w") as f:
                f.write(code)

            flags = self.config.compiler_flags.split()
            cmd = [
                self.COMPILER,
                self.STD_FLAG,
                *flags,
                "-S",
                "-masm=intel",
                "-o", asm_out,
                asm_src,
            ]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if result.returncode != 0:
                return None

            if not os.path.isfile(asm_out):
                return None

            with open(asm_out) as f:
                asm_text = f.read()

            # Parse the kernel's function signature to find its name
            sig = parse_function_signature(code)
            if sig is None:
                # Return the first 50 non-directive lines
                lines = [l for l in asm_text.splitlines() if not l.strip().startswith('.')]
                return "\n".join(lines[:50])

            # Find the function label in the assembly
            func_name = sig.name
            lines = asm_text.splitlines()
            start_idx = None
            for i, line in enumerate(lines):
                # Look for the function label (e.g., "reduce:" or mangled name containing func_name)
                stripped = line.strip()
                if stripped.endswith(":") and func_name in stripped:
                    start_idx = i
                    break

            if start_idx is None:
                # Fallback: return first 50 meaningful lines
                meaningful = [l for l in lines if l.strip() and not l.strip().startswith('.cfi')]
                return "\n".join(meaningful[:50])

            # Extract from function label until next function or end
            func_lines = []
            for line in lines[start_idx:]:
                func_lines.append(line)
                if len(func_lines) >= 50:
                    break
                # Stop at .size directive for this function (end of function)
                if line.strip().startswith('.size') and func_name in line:
                    break

            return "\n".join(func_lines) if func_lines else None

        except Exception:
            return None

    def build(self, code: str) -> None:
        """Compile *code* (kernel source) into a benchmarkable binary.

        Raises ``RuntimeError`` on compilation failure.
        """
        # Write kernel source to workdir
        with open(self._kernel_path, "w") as f:
            f.write(code)

        # Check for custom harness (e.g., kernels/pow_int_harness.cpp)
        custom_harness = self.config.kernel_path.replace(".cpp", "_harness.cpp")
        if os.path.isfile(custom_harness):
            import shutil
            shutil.copy(custom_harness, self._harness_path)
        else:
            # Locate header
            header_path = self._find_header()

            # Generate harness
            harness_src = self._generate_harness(code, header_path)
            with open(self._harness_path, "w") as f:
                f.write(harness_src)

        # Compile
        flags = self.config.compiler_flags.split()
        cmd = [
            self.COMPILER,
            self.STD_FLAG,
            *flags,
            "-I", self._workdir,
            "-o", self._binary_path,
            self._harness_path,
            "-lrt",
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(
                f"{self.LANGUAGE_NAME} build failed (exit {result.returncode}):\n"
                f"Command: {' '.join(cmd)}\n"
                f"--- stderr ---\n{result.stderr}\n"
                f"--- stdout ---\n{result.stdout}"
            )

    def test(self) -> bool:
        """Run correctness tests.  Return True if all pass."""
        if not os.path.isfile(self._binary_path):
            raise RuntimeError("Binary not found. Call build() first.")

        result = self._run_sandboxed([self._binary_path, "--test"])
        if result.returncode != 0:
            print(f"[AutoPerf] Test FAILED (exit {result.returncode})")
            if result.stderr:
                print(result.stderr)
            return False
        return True

    def benchmark(self) -> float:
        """Run benchmark and return ns/op.

        Raises ``RuntimeError`` if the binary cannot be run or the output
        cannot be parsed.
        """
        if not os.path.isfile(self._binary_path):
            raise RuntimeError("Binary not found. Call build() first.")

        result = self._run_sandboxed([self._binary_path, "--bench"])
        if result.returncode != 0:
            raise RuntimeError(
                f"Benchmark failed (exit {result.returncode}):\n"
                f"stderr: {result.stderr}\nstdout: {result.stdout}"
            )

        # Parse JSON from stdout
        stdout = result.stdout.strip()
        try:
            data = json.loads(stdout)
            return float(data["ns_per_op"])
        except (json.JSONDecodeError, KeyError) as exc:
            raise RuntimeError(
                f"Could not parse benchmark output: {exc}\n"
                f"Raw stdout: {stdout!r}"
            ) from exc
