import os
import re
import subprocess

from orchestrator.src.config import (
    CPP_ROOT,
    CONFIGURE_TIMEOUT_S,
    BUILD_TIMEOUT_S,
    TEST_TIMEOUT_S,
    BENCH_TIMEOUT_S,
    KERNEL_TYPES,
    KERNEL_BASENAMES,
)
from orchestrator.src.errors import (
    ConfigureError,
    BuildError,
    TestError,
    BenchmarkError,
    BenchmarkParseError,
    OperationTimeout,
)


class CppProject:
    """Manages the C++ project for a given kernel."""

    def __init__(self, path, kernel_type):
        self.path = path
        os.makedirs(self.path, exist_ok=True)
        
        # Only copy the project if it doesn't exist or is empty
        if not os.path.exists(os.path.join(self.path, "CMakeLists.txt")):
            # Copy the entire C++ project to the temporary path
            subprocess.run(['cp', '-r', f'{CPP_ROOT}/.', str(self.path)], check=True)
        
        self.kernel_type = kernel_type
        self._source_dir = self.path # Source directory is now the temporary path
        self._build_dir = os.path.join(self.path, "build")

        if kernel_type not in KERNEL_TYPES:
            raise ValueError(f"Unknown kernel type: {kernel_type}")

    def update_kernel(self, kernel_code):
        """Updates the kernel.cpp file with the given code."""
        basename = KERNEL_BASENAMES.get(self.kernel_type)
        target_kernel_file = os.path.join(self._source_dir, "src", basename) if basename else None
        if target_kernel_file:
            with open(target_kernel_file, 'w', encoding='utf-8') as f:
                f.write(kernel_code)
        else:
            raise ValueError(f"Unknown kernel type: {self.kernel_type}")

    def _run_command(self, command, timeout):
        try:
            result = subprocess.run(
                command,
                cwd=self.path,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except subprocess.TimeoutExpired as e:
            raise OperationTimeout(command[0], f"{e}") from e
        except OSError as e:
            raise BuildError(f"OS error: {e}") from e

        success = result.returncode == 0
        log = result.stdout + result.stderr
        return success, log

    def configure(self, enable_benches=True, enable_tests=True):
        """Configures the CMake project for the selected kernel only."""
        # Clean build directory to avoid CMake cache conflicts
        if os.path.exists(self._build_dir):
            import shutil
            shutil.rmtree(self._build_dir)
        os.makedirs(self._build_dir, exist_ok=True)

        cmake_args = [
            f"-S{self._source_dir}",
            f"-B{self._build_dir}",
            f"-DAUTOPERF_KERNELS={self.kernel_type}",
            f"-DAUTOPERF_ENABLE_BENCHES={'ON' if enable_benches else 'OFF'}",
            f"-DAUTOPERF_ENABLE_TESTS={'ON' if enable_tests else 'OFF'}",
        ]
        command = ["cmake", *cmake_args]
        ok, log = self._run_command(command, CONFIGURE_TIMEOUT_S)
        if not ok:
            raise ConfigureError(log)
        return ok, log

    def build(self, target: str | None = None):
        """Builds the C++ project. If target is provided, only builds that target."""
        if target:
            command = ["cmake", "--build", str(self._build_dir), "--target", target, "--parallel", "8"]
        else:
            command = ["cmake", "--build", str(self._build_dir), "--parallel", "8"]
        ok, log = self._run_command(command, BUILD_TIMEOUT_S)
        if not ok:
            raise BuildError(log)
        return ok, log

    def test(self):
        """Runs the tests for the selected kernel only."""
        # Only the tests_<kernel> target will be generated by CMake
        command = ["ctest", "--test-dir", str(self._build_dir), "--output-on-failure"]
        ok, log = self._run_command(command, TEST_TIMEOUT_S)
        if not ok:
            raise TestError(log)
        return ok, log

    def benchmark(self):
        """Runs the benchmark for the selected kernel and extracts the score."""
        benchmark_executable = os.path.join(self._build_dir, "bin", f"bench_{self.kernel_type}")

        if not os.path.exists(benchmark_executable):
            raise BenchmarkError(f"Benchmark executable not found: {benchmark_executable}")

        # Run the benchmark for the specific kernel
        kernel_name_for_regex = self.kernel_type

        command = [str(benchmark_executable)]
        success, log = self._run_command(command, BENCH_TIMEOUT_S)

        score = None
        if success:
            pattern = re.compile(rf"BM_{kernel_name_for_regex}(?:/\d+)*\s+(\d+\.?\d*)\s+ns")
            matches = pattern.findall(log)

            if matches:
                # Sum all benchmark scores for different sizes
                scores = [float(match) for match in matches]
                score = sum(scores)
                log += f"\nFound {len(scores)} benchmark measurements: {scores} -> Total: {score:.2f} ns"
            else:
                raise BenchmarkParseError(
                    f"Failed to parse benchmark scores for {kernel_name_for_regex} from output.\n{log}"
                )

        if not success:
            raise BenchmarkError(log)
        return success, log, score
